document.addEventListener('DOMContentLoaded', () => {
    const cursor = document.getElementById('custom-cursor');
    const button = document.getElementById('the-button');
    const jokeContainer = document.getElementById('random-joke');
    const loading = document.getElementById('loading');
    const loadingText = document.getElementById('loading-text');
    const footerText = document.getElementById('footer-text');
    const subtext = document.querySelector('.subtext');
    const rareOverlay = document.getElementById('rare-overlay');

    // 1. Cursor Logic (Smooth Physics)
    let mouseX = window.innerWidth / 2;
    let mouseY = window.innerHeight / 2;
    let cursorX = window.innerWidth / 2;
    let cursorY = window.innerHeight / 2;

    document.addEventListener('mousemove', (e) => {
        mouseX = e.clientX;
        mouseY = e.clientY;
    });

    function animateCursor() {
        // Lerp factor (0.1 = smooth, 0.2 = faster)
        const speed = 0.15;

        cursorX += (mouseX - cursorX) * speed;
        cursorY += (mouseY - cursorY) * speed;

        cursor.style.left = cursorX + 'px';
        cursor.style.top = cursorY + 'px';

        requestAnimationFrame(animateCursor);
    }
    animateCursor();

    // 2. Button Logic
    const originalText = "DO THE THING";
    const hoverTexts = [
        "don’t act surprised",
        "still hovering? interesting.",
        "last chance to behave",
        "you’re already committed",
        "go on. you came this far.",
        "this is a long hover",
        "thinking won’t save you",
        "you’re not fooling anyone",
        "we both know you want to",
        "hesitation noted",
        "this is getting personal",
        "you’re enjoying this",
        "at least pretend to resist",
        "curiosity is loud today",
        "this is on you now",
        "making eye contact with a button, huh?",
        "bold of you to hover this long",
        "self-control is slipping",
        "just click it already",
        "you didn’t open this to stop"
    ];
    const clickText = "oh.\nokay then.";

    // Fake loading texts
    const loadingTexts = [
        "That was intentional.",
        "No backing out now.",
        "Interesting decision.",
        "This escalated quickly.",
        "You chose this."
    ];

    // Rare messages options
    const rareMessages = [
        "Slow down.<br><br><span style='font-size: 2rem'>You didn’t even pause.</span>",
        "Relax.<br><br><span style='font-size: 2rem'>You knew exactly what you were doing.</span>",
        "You again?<br><br><span style='font-size: 2rem'>At this point, it’s a pattern.</span>"
    ];

    button.addEventListener('mouseover', () => {
        const randomText = hoverTexts[Math.floor(Math.random() * hoverTexts.length)];
        button.innerText = randomText;
    });

    button.addEventListener('mouseout', () => {
        button.innerText = originalText;
    });

    button.addEventListener('click', () => {
        button.innerText = "oh. okay then.";
        button.disabled = true;
        button.style.transform = 'scale(0.95)';
        subtext.style.visibility = 'hidden';

        // 1% Chance for RARE MESSAGE
        if (Math.random() < 0.01) {
            // Rare Event
            const msg = rareMessages[Math.floor(Math.random() * rareMessages.length)];
            rareOverlay.innerHTML = msg;

            setTimeout(() => {
                rareOverlay.style.display = 'flex'; // Force show
            }, 100);

            setTimeout(() => {
                doRedirect();
            }, 2500); // Longer delay to read
        } else {
            // Normal Event
            setTimeout(() => {
                loading.classList.add('visible');
                loading.classList.remove('hidden');
                loadingText.innerText = loadingTexts[Math.floor(Math.random() * loadingTexts.length)];
            }, 200);

            setTimeout(() => {
                doRedirect();
            }, 800);
        }
    });

    function doRedirect() {
        const randomSite = websites[Math.floor(Math.random() * websites.length)];
        window.open(randomSite, '_blank');

        // Reset state
        setTimeout(() => {
            button.disabled = false;
            button.innerText = originalText;
            button.style.transform = 'scale(1)';
            subtext.style.visibility = 'visible';
            loading.classList.remove('visible');
            loading.classList.add('hidden');
            rareOverlay.style.display = 'none';
        }, 1000);
    }

    // 3. Random Jokes
    const jokes = [
        "No data collected. We don’t care that much.",
        "This website has no terms. You already lost.",
        "Built with love, boredom, and poor decisions.",
        "If this breaks, that’s part of the experience.",
        "Your expectations are too high."
    ];

    jokeContainer.innerText = jokes[Math.floor(Math.random() * jokes.length)];

    // 5. Random Emoji Spawn
    function spawnEmoji() {
        const emojis = ['🤡', '💩', '👻', '💀', '🍌', '👀'];
        const el = document.createElement('div');
        el.innerText = emojis[Math.floor(Math.random() * emojis.length)];
        el.style.position = 'fixed';
        el.style.left = Math.random() * window.innerWidth + 'px';
        el.style.top = Math.random() * window.innerHeight + 'px';
        el.style.fontSize = '2rem';
        el.style.pointerEvents = 'none';
        el.style.zIndex = '5';
        document.body.appendChild(el);
    }

    if (Math.random() > 0.5) {
        spawnEmoji();
    }

    // 6. The List
    let websites = [
        "https://neal.fun/?r=1",
        "https://pointerpointer.com/?r=2",
        "https://eelslap.com/?r=3",
        "https://catbounce.com/?r=4",
        "https://corndog.io/?r=5",
        "https://heeeeeeeey.com/?r=6",
        "https://staggeringbeauty.com/?r=7",
        "https://zoomquilt.org/?r=8",
        "https://bouncingdvdlogo.com/?r=9",
        "https://longdogechallenge.com/?r=10",
        "https://hackertyper.com/?r=11",
        "https://findtheinvisiblecow.com/?r=12",
        "https://alwaysjudgeabookbyitscover.com/?r=13",
        "https://thisiswhyimbroke.com/?r=14",
        "https://mapcrunch.com/?r=15",
        "https://littlealchemy2.com/?r=16",
        "https://patatap.com/?r=17",
        "https://onemillioncheckboxes.com/?r=18",
        "https://mackerelmediafish.com/?r=19",
        "https://koalastothemax.com/?r=20",
        "https://neal.fun/?r=21",
        "https://pointerpointer.com/?r=22",
        "https://eelslap.com/?r=23",
        "https://catbounce.com/?r=24",
        "https://corndog.io/?r=25",
        "https://heeeeeeeey.com/?r=26",
        "https://staggeringbeauty.com/?r=27",
        "https://zoomquilt.org/?r=28",
        "https://bouncingdvdlogo.com/?r=29",
        "https://longdogechallenge.com/?r=30",
        "https://hackertyper.com/?r=31",
        "https://findtheinvisiblecow.com/?r=32",
        "https://alwaysjudgeabookbyitscover.com/?r=33",
        "https://thisiswhyimbroke.com/?r=34",
        "https://mapcrunch.com/?r=35",
        "https://littlealchemy2.com/?r=36",
        "https://patatap.com/?r=37",
        "https://onemillioncheckboxes.com/?r=38",
        "https://mackerelmediafish.com/?r=39",
        "https://koalastothemax.com/?r=40",
        "https://neal.fun/?r=41",
        "https://pointerpointer.com/?r=42",
        "https://eelslap.com/?r=43",
        "https://catbounce.com/?r=44",
        "https://corndog.io/?r=45",
        "https://heeeeeeeey.com/?r=46",
        "https://staggeringbeauty.com/?r=47",
        "https://zoomquilt.org/?r=48",
        "https://bouncingdvdlogo.com/?r=49",
        "https://longdogechallenge.com/?r=50",
        "https://hackertyper.com/?r=51",
        "https://findtheinvisiblecow.com/?r=52",
        "https://alwaysjudgeabookbyitscover.com/?r=53",
        "https://thisiswhyimbroke.com/?r=54",
        "https://mapcrunch.com/?r=55",
        "https://littlealchemy2.com/?r=56",
        "https://patatap.com/?r=57",
        "https://onemillioncheckboxes.com/?r=58",
        "https://mackerelmediafish.com/?r=59",
        "https://koalastothemax.com/?r=60",
        "https://neal.fun/?r=61",
        "https://pointerpointer.com/?r=62",
        "https://eelslap.com/?r=63",
        "https://catbounce.com/?r=64",
        "https://corndog.io/?r=65",
        "https://heeeeeeeey.com/?r=66",
        "https://staggeringbeauty.com/?r=67",
        "https://zoomquilt.org/?r=68",
        "https://bouncingdvdlogo.com/?r=69",
        "https://longdogechallenge.com/?r=70",
        "https://hackertyper.com/?r=71",
        "https://findtheinvisiblecow.com/?r=72",
        "https://alwaysjudgeabookbyitscover.com/?r=73",
        "https://thisiswhyimbroke.com/?r=74",
        "https://mapcrunch.com/?r=75",
        "https://littlealchemy2.com/?r=76",
        "https://patatap.com/?r=77",
        "https://onemillioncheckboxes.com/?r=78",
        "https://mackerelmediafish.com/?r=79",
        "https://koalastothemax.com/?r=80",
        "https://neal.fun/?r=81",
        "https://pointerpointer.com/?r=82",
        "https://eelslap.com/?r=83",
        "https://catbounce.com/?r=84",
        "https://corndog.io/?r=85",
        "https://heeeeeeeey.com/?r=86",
        "https://staggeringbeauty.com/?r=87",
        "https://zoomquilt.org/?r=88",
        "https://bouncingdvdlogo.com/?r=89",
        "https://longdogechallenge.com/?r=90",
        "https://hackertyper.com/?r=91",
        "https://findtheinvisiblecow.com/?r=92",
        "https://alwaysjudgeabookbyitscover.com/?r=93",
        "https://thisiswhyimbroke.com/?r=94",
        "https://mapcrunch.com/?r=95",
        "https://littlealchemy2.com/?r=96",
        "https://patatap.com/?r=97",
        "https://onemillioncheckboxes.com/?r=98",
        "https://mackerelmediafish.com/?r=99",
        "https://koalastothemax.com/?r=100",
        "https://neal.fun/?r=101",
        "https://pointerpointer.com/?r=102",
        "https://eelslap.com/?r=103",
        "https://catbounce.com/?r=104",
        "https://corndog.io/?r=105",
        "https://heeeeeeeey.com/?r=106",
        "https://staggeringbeauty.com/?r=107",
        "https://zoomquilt.org/?r=108",
        "https://bouncingdvdlogo.com/?r=109",
        "https://longdogechallenge.com/?r=110",
        "https://hackertyper.com/?r=111",
        "https://findtheinvisiblecow.com/?r=112",
        "https://alwaysjudgeabookbyitscover.com/?r=113",
        "https://thisiswhyimbroke.com/?r=114",
        "https://mapcrunch.com/?r=115",
        "https://littlealchemy2.com/?r=116",
        "https://patatap.com/?r=117",
        "https://onemillioncheckboxes.com/?r=118",
        "https://mackerelmediafish.com/?r=119",
        "https://koalastothemax.com/?r=120",
        "https://neal.fun/?r=121",
        "https://pointerpointer.com/?r=122",
        "https://eelslap.com/?r=123",
        "https://catbounce.com/?r=124",
        "https://corndog.io/?r=125",
        "https://heeeeeeeey.com/?r=126",
        "https://staggeringbeauty.com/?r=127",
        "https://zoomquilt.org/?r=128",
        "https://bouncingdvdlogo.com/?r=129",
        "https://longdogechallenge.com/?r=130",
        "https://hackertyper.com/?r=131",
        "https://findtheinvisiblecow.com/?r=132",
        "https://alwaysjudgeabookbyitscover.com/?r=133",
        "https://thisiswhyimbroke.com/?r=134",
        "https://mapcrunch.com/?r=135",
        "https://littlealchemy2.com/?r=136",
        "https://patatap.com/?r=137",
        "https://onemillioncheckboxes.com/?r=138",
        "https://mackerelmediafish.com/?r=139",
        "https://koalastothemax.com/?r=140",
        "https://neal.fun/?r=141",
        "https://pointerpointer.com/?r=142",
        "https://eelslap.com/?r=143",
        "https://catbounce.com/?r=144",
        "https://corndog.io/?r=145",
        "https://heeeeeeeey.com/?r=146",
        "https://staggeringbeauty.com/?r=147",
        "https://zoomquilt.org/?r=148",
        "https://bouncingdvdlogo.com/?r=149",
        "https://longdogechallenge.com/?r=150",
        "https://hackertyper.com/?r=151",
        "https://findtheinvisiblecow.com/?r=152",
        "https://alwaysjudgeabookbyitscover.com/?r=153",
        "https://thisiswhyimbroke.com/?r=154",
        "https://mapcrunch.com/?r=155",
        "https://littlealchemy2.com/?r=156",
        "https://patatap.com/?r=157",
        "https://onemillioncheckboxes.com/?r=158",
        "https://mackerelmediafish.com/?r=159",
        "https://koalastothemax.com/?r=160",
        "https://neal.fun/?r=161",
        "https://pointerpointer.com/?r=162",
        "https://eelslap.com/?r=163",
        "https://catbounce.com/?r=164",
        "https://corndog.io/?r=165",
        "https://heeeeeeeey.com/?r=166",
        "https://staggeringbeauty.com/?r=167",
        "https://zoomquilt.org/?r=168",
        "https://bouncingdvdlogo.com/?r=169",
        "https://longdogechallenge.com/?r=170",
        "https://hackertyper.com/?r=171",
        "https://findtheinvisiblecow.com/?r=172",
        "https://alwaysjudgeabookbyitscover.com/?r=173",
        "https://thisiswhyimbroke.com/?r=174",
        "https://mapcrunch.com/?r=175",
        "https://littlealchemy2.com/?r=176",
        "https://patatap.com/?r=177",
        "https://onemillioncheckboxes.com/?r=178",
        "https://mackerelmediafish.com/?r=179",
        "https://koalastothemax.com/?r=180",
        "https://neal.fun/?r=181",
        "https://pointerpointer.com/?r=182",
        "https://eelslap.com/?r=183",
        "https://catbounce.com/?r=184",
        "https://corndog.io/?r=185",
        "https://heeeeeeeey.com/?r=186",
        "https://staggeringbeauty.com/?r=187",
        "https://zoomquilt.org/?r=188",
        "https://bouncingdvdlogo.com/?r=189",
        "https://longdogechallenge.com/?r=190",
        "https://hackertyper.com/?r=191",
        "https://findtheinvisiblecow.com/?r=192",
        "https://alwaysjudgeabookbyitscover.com/?r=193",
        "https://thisiswhyimbroke.com/?r=194",
        "https://mapcrunch.com/?r=195",
        "https://littlealchemy2.com/?r=196",
        "https://patatap.com/?r=197",
        "https://onemillioncheckboxes.com/?r=198",
        "https://mackerelmediafish.com/?r=199",
        "https://koalastothemax.com/?r=200",
        "https://neal.fun/?r=201",
        "https://pointerpointer.com/?r=202",
        "https://eelslap.com/?r=203",
        "https://catbounce.com/?r=204",
        "https://corndog.io/?r=205",
        "https://heeeeeeeey.com/?r=206",
        "https://staggeringbeauty.com/?r=207",
        "https://zoomquilt.org/?r=208",
        "https://bouncingdvdlogo.com/?r=209",
        "https://longdogechallenge.com/?r=210",
        "https://hackertyper.com/?r=211",
        "https://findtheinvisiblecow.com/?r=212",
        "https://alwaysjudgeabookbyitscover.com/?r=213",
        "https://thisiswhyimbroke.com/?r=214",
        "https://mapcrunch.com/?r=215",
        "https://littlealchemy2.com/?r=216",
        "https://patatap.com/?r=217",
        "https://onemillioncheckboxes.com/?r=218",
        "https://mackerelmediafish.com/?r=219",
        "https://koalastothemax.com/?r=220",
        "https://neal.fun/?r=221",
        "https://pointerpointer.com/?r=222",
        "https://eelslap.com/?r=223",
        "https://catbounce.com/?r=224",
        "https://corndog.io/?r=225",
        "https://heeeeeeeey.com/?r=226",
        "https://staggeringbeauty.com/?r=227",
        "https://zoomquilt.org/?r=228",
        "https://bouncingdvdlogo.com/?r=229",
        "https://longdogechallenge.com/?r=230",
        "https://hackertyper.com/?r=231",
        "https://findtheinvisiblecow.com/?r=232",
        "https://alwaysjudgeabookbyitscover.com/?r=233",
        "https://thisiswhyimbroke.com/?r=234",
        "https://mapcrunch.com/?r=235",
        "https://littlealchemy2.com/?r=236",
        "https://patatap.com/?r=237",
        "https://onemillioncheckboxes.com/?r=238",
        "https://mackerelmediafish.com/?r=239",
        "https://koalastothemax.com/?r=240",
        "https://neal.fun/?r=241",
        "https://pointerpointer.com/?r=242",
        "https://eelslap.com/?r=243",
        "https://catbounce.com/?r=244",
        "https://corndog.io/?r=245",
        "https://heeeeeeeey.com/?r=246",
        "https://staggeringbeauty.com/?r=247",
        "https://zoomquilt.org/?r=248",
        "https://bouncingdvdlogo.com/?r=249",
        "https://longdogechallenge.com/?r=250",
        "https://hackertyper.com/?r=251",
        "https://findtheinvisiblecow.com/?r=252",
        "https://alwaysjudgeabookbyitscover.com/?r=253",
        "https://thisiswhyimbroke.com/?r=254",
        "https://mapcrunch.com/?r=255",
        "https://littlealchemy2.com/?r=256",
        "https://patatap.com/?r=257",
        "https://onemillioncheckboxes.com/?r=258",
        "https://mackerelmediafish.com/?r=259",
        "https://koalastothemax.com/?r=260",
        "https://neal.fun/?r=261",
        "https://pointerpointer.com/?r=262",
        "https://eelslap.com/?r=263",
        "https://catbounce.com/?r=264",
        "https://corndog.io/?r=265",
        "https://heeeeeeeey.com/?r=266",
        "https://staggeringbeauty.com/?r=267",
        "https://zoomquilt.org/?r=268",
        "https://bouncingdvdlogo.com/?r=269",
        "https://longdogechallenge.com/?r=270",
        "https://hackertyper.com/?r=271",
        "https://findtheinvisiblecow.com/?r=272",
        "https://alwaysjudgeabookbyitscover.com/?r=273",
        "https://thisiswhyimbroke.com/?r=274",
        "https://mapcrunch.com/?r=275",
        "https://littlealchemy2.com/?r=276",
        "https://patatap.com/?r=277",
        "https://onemillioncheckboxes.com/?r=278",
        "https://mackerelmediafish.com/?r=279",
        "https://koalastothemax.com/?r=280",
        "https://neal.fun/?r=281",
        "https://pointerpointer.com/?r=282",
        "https://eelslap.com/?r=283",
        "https://catbounce.com/?r=284",
        "https://corndog.io/?r=285",
        "https://heeeeeeeey.com/?r=286",
        "https://staggeringbeauty.com/?r=287",
        "https://zoomquilt.org/?r=288",
        "https://bouncingdvdlogo.com/?r=289",
        "https://longdogechallenge.com/?r=290",
        "https://hackertyper.com/?r=291",
        "https://findtheinvisiblecow.com/?r=292",
        "https://alwaysjudgeabookbyitscover.com/?r=293",
        "https://thisiswhyimbroke.com/?r=294",
        "https://mapcrunch.com/?r=295",
        "https://littlealchemy2.com/?r=296",
        "https://patatap.com/?r=297",
        "https://onemillioncheckboxes.com/?r=298",
        "https://mackerelmediafish.com/?r=299",
        "https://koalastothemax.com/?r=300",
        "https://neal.fun/?r=301",
        "https://pointerpointer.com/?r=302",
        "https://eelslap.com/?r=303",
        "https://catbounce.com/?r=304",
        "https://corndog.io/?r=305",
        "https://heeeeeeeey.com/?r=306",
        "https://staggeringbeauty.com/?r=307",
        "https://zoomquilt.org/?r=308",
        "https://bouncingdvdlogo.com/?r=309",
        "https://longdogechallenge.com/?r=310",
        "https://hackertyper.com/?r=311",
        "https://findtheinvisiblecow.com/?r=312",
        "https://alwaysjudgeabookbyitscover.com/?r=313",
        "https://thisiswhyimbroke.com/?r=314",
        "https://mapcrunch.com/?r=315",
        "https://littlealchemy2.com/?r=316",
        "https://patatap.com/?r=317",
        "https://onemillioncheckboxes.com/?r=318",
        "https://mackerelmediafish.com/?r=319",
        "https://koalastothemax.com/?r=320",
        "https://neal.fun/?r=321",
        "https://pointerpointer.com/?r=322",
        "https://eelslap.com/?r=323",
        "https://catbounce.com/?r=324",
        "https://corndog.io/?r=325",
        "https://heeeeeeeey.com/?r=326",
        "https://staggeringbeauty.com/?r=327",
        "https://zoomquilt.org/?r=328",
        "https://bouncingdvdlogo.com/?r=329",
        "https://longdogechallenge.com/?r=330",
        "https://hackertyper.com/?r=331",
        "https://findtheinvisiblecow.com/?r=332",
        "https://alwaysjudgeabookbyitscover.com/?r=333",
        "https://thisiswhyimbroke.com/?r=334",
        "https://mapcrunch.com/?r=335",
        "https://littlealchemy2.com/?r=336",
        "https://patatap.com/?r=337",
        "https://onemillioncheckboxes.com/?r=338",
        "https://mackerelmediafish.com/?r=339",
        "https://koalastothemax.com/?r=340",
        "https://neal.fun/?r=341",
        "https://pointerpointer.com/?r=342",
        "https://eelslap.com/?r=343",
        "https://catbounce.com/?r=344",
        "https://corndog.io/?r=345",
        "https://heeeeeeeey.com/?r=346",
        "https://staggeringbeauty.com/?r=347",
        "https://zoomquilt.org/?r=348",
        "https://bouncingdvdlogo.com/?r=349",
        "https://longdogechallenge.com/?r=350",
        "https://hackertyper.com/?r=351",
        "https://findtheinvisiblecow.com/?r=352",
        "https://alwaysjudgeabookbyitscover.com/?r=353",
        "https://thisiswhyimbroke.com/?r=354",
        "https://mapcrunch.com/?r=355",
        "https://littlealchemy2.com/?r=356",
        "https://patatap.com/?r=357",
        "https://onemillioncheckboxes.com/?r=358",
        "https://mackerelmediafish.com/?r=359",
        "https://koalastothemax.com/?r=360",
        "https://neal.fun/?r=361",
        "https://pointerpointer.com/?r=362",
        "https://eelslap.com/?r=363",
        "https://catbounce.com/?r=364",
        "https://corndog.io/?r=365",
        "https://heeeeeeeey.com/?r=366",
        "https://staggeringbeauty.com/?r=367",
        "https://zoomquilt.org/?r=368",
        "https://bouncingdvdlogo.com/?r=369",
        "https://longdogechallenge.com/?r=370",
        "https://hackertyper.com/?r=371",
        "https://findtheinvisiblecow.com/?r=372",
        "https://alwaysjudgeabookbyitscover.com/?r=373",
        "https://thisiswhyimbroke.com/?r=374",
        "https://mapcrunch.com/?r=375",
        "https://littlealchemy2.com/?r=376",
        "https://patatap.com/?r=377",
        "https://onemillioncheckboxes.com/?r=378",
        "https://mackerelmediafish.com/?r=379",
        "https://koalastothemax.com/?r=380",
        "https://neal.fun/?r=381",
        "https://pointerpointer.com/?r=382",
        "https://eelslap.com/?r=383",
        "https://catbounce.com/?r=384",
        "https://corndog.io/?r=385",
        "https://heeeeeeeey.com/?r=386",
        "https://staggeringbeauty.com/?r=387",
        "https://zoomquilt.org/?r=388",
        "https://bouncingdvdlogo.com/?r=389",
        "https://longdogechallenge.com/?r=390",
        "https://hackertyper.com/?r=391",
        "https://findtheinvisiblecow.com/?r=392",
        "https://alwaysjudgeabookbyitscover.com/?r=393",
        "https://thisiswhyimbroke.com/?r=394",
        "https://mapcrunch.com/?r=395",
        "https://littlealchemy2.com/?r=396",
        "https://patatap.com/?r=397",
        "https://onemillioncheckboxes.com/?r=398",
        "https://mackerelmediafish.com/?r=399",
        "https://koalastothemax.com/?r=400",
        "https://neal.fun/?r=401",
        "https://pointerpointer.com/?r=402",
        "https://eelslap.com/?r=403",
        "https://catbounce.com/?r=404",
        "https://corndog.io/?r=405",
        "https://heeeeeeeey.com/?r=406",
        "https://staggeringbeauty.com/?r=407",
        "https://zoomquilt.org/?r=408",
        "https://bouncingdvdlogo.com/?r=409",
        "https://longdogechallenge.com/?r=410",
        "https://hackertyper.com/?r=411",
        "https://findtheinvisiblecow.com/?r=412",
        "https://alwaysjudgeabookbyitscover.com/?r=413",
        "https://thisiswhyimbroke.com/?r=414",
        "https://mapcrunch.com/?r=415",
        "https://littlealchemy2.com/?r=416",
        "https://patatap.com/?r=417",
        "https://onemillioncheckboxes.com/?r=418",
        "https://mackerelmediafish.com/?r=419",
        "https://koalastothemax.com/?r=420",
        "https://neal.fun/?r=421",
        "https://pointerpointer.com/?r=422",
        "https://eelslap.com/?r=423",
        "https://catbounce.com/?r=424",
        "https://corndog.io/?r=425",
        "https://heeeeeeeey.com/?r=426",
        "https://staggeringbeauty.com/?r=427",
        "https://zoomquilt.org/?r=428",
        "https://bouncingdvdlogo.com/?r=429",
        "https://longdogechallenge.com/?r=430",
        "https://hackertyper.com/?r=431",
        "https://findtheinvisiblecow.com/?r=432",
        "https://alwaysjudgeabookbyitscover.com/?r=433",
        "https://thisiswhyimbroke.com/?r=434",
        "https://mapcrunch.com/?r=435",
        "https://littlealchemy2.com/?r=436",
        "https://patatap.com/?r=437",
        "https://onemillioncheckboxes.com/?r=438",
        "https://mackerelmediafish.com/?r=439",
        "https://koalastothemax.com/?r=440",
        "https://neal.fun/?r=441",
        "https://pointerpointer.com/?r=442",
        "https://eelslap.com/?r=443",
        "https://catbounce.com/?r=444",
        "https://corndog.io/?r=445",
        "https://heeeeeeeey.com/?r=446",
        "https://staggeringbeauty.com/?r=447",
        "https://zoomquilt.org/?r=448",
        "https://bouncingdvdlogo.com/?r=449",
        "https://longdogechallenge.com/?r=450",
        "https://hackertyper.com/?r=451",
        "https://findtheinvisiblecow.com/?r=452",
        "https://alwaysjudgeabookbyitscover.com/?r=453",
        "https://thisiswhyimbroke.com/?r=454",
        "https://mapcrunch.com/?r=455",
        "https://littlealchemy2.com/?r=456",
        "https://patatap.com/?r=457",
        "https://onemillioncheckboxes.com/?r=458",
        "https://mackerelmediafish.com/?r=459",
        "https://koalastothemax.com/?r=460",
        "https://neal.fun/?r=461",
        "https://pointerpointer.com/?r=462",
        "https://eelslap.com/?r=463",
        "https://catbounce.com/?r=464",
        "https://corndog.io/?r=465",
        "https://heeeeeeeey.com/?r=466",
        "https://staggeringbeauty.com/?r=467",
        "https://zoomquilt.org/?r=468",
        "https://bouncingdvdlogo.com/?r=469",
        "https://longdogechallenge.com/?r=470",
        "https://hackertyper.com/?r=471",
        "https://findtheinvisiblecow.com/?r=472",
        "https://alwaysjudgeabookbyitscover.com/?r=473",
        "https://thisiswhyimbroke.com/?r=474",
        "https://mapcrunch.com/?r=475",
        "https://littlealchemy2.com/?r=476",
        "https://patatap.com/?r=477",
        "https://onemillioncheckboxes.com/?r=478",
        "https://mackerelmediafish.com/?r=479",
        "https://koalastothemax.com/?r=480",
        "https://neal.fun/?r=481",
        "https://pointerpointer.com/?r=482",
        "https://eelslap.com/?r=483",
        "https://catbounce.com/?r=484",
        "https://corndog.io/?r=485",
        "https://heeeeeeeey.com/?r=486",
        "https://staggeringbeauty.com/?r=487",
        "https://zoomquilt.org/?r=488",
        "https://bouncingdvdlogo.com/?r=489",
        "https://longdogechallenge.com/?r=490",
        "https://hackertyper.com/?r=491",
        "https://findtheinvisiblecow.com/?r=492",
        "https://alwaysjudgeabookbyitscover.com/?r=493",
        "https://thisiswhyimbroke.com/?r=494",
        "https://mapcrunch.com/?r=495",
        "https://littlealchemy2.com/?r=496",
        "https://patatap.com/?r=497",
        "https://onemillioncheckboxes.com/?r=498",
        "https://mackerelmediafish.com/?r=499",
        "https://koalastothemax.com/?r=500",
        "https://neal.fun/?r=501",
        "https://pointerpointer.com/?r=502",
        "https://eelslap.com/?r=503",
        "https://catbounce.com/?r=504",
        "https://corndog.io/?r=505",
        "https://heeeeeeeey.com/?r=506",
        "https://staggeringbeauty.com/?r=507",
        "https://zoomquilt.org/?r=508",
        "https://bouncingdvdlogo.com/?r=509",
        "https://longdogechallenge.com/?r=510",
        "https://hackertyper.com/?r=511",
        "https://findtheinvisiblecow.com/?r=512",
        "https://alwaysjudgeabookbyitscover.com/?r=513",
        "https://thisiswhyimbroke.com/?r=514",
        "https://mapcrunch.com/?r=515",
        "https://littlealchemy2.com/?r=516",
        "https://patatap.com/?r=517",
        "https://onemillioncheckboxes.com/?r=518",
        "https://mackerelmediafish.com/?r=519",
        "https://koalastothemax.com/?r=520",
        "https://neal.fun/?r=521",
        "https://pointerpointer.com/?r=522",
        "https://eelslap.com/?r=523",
        "https://catbounce.com/?r=524",
        "https://corndog.io/?r=525",
        "https://heeeeeeeey.com/?r=526",
        "https://staggeringbeauty.com/?r=527",
        "https://zoomquilt.org/?r=528",
        "https://bouncingdvdlogo.com/?r=529",
        "https://longdogechallenge.com/?r=530",
        "https://hackertyper.com/?r=531",
        "https://findtheinvisiblecow.com/?r=532",
        "https://alwaysjudgeabookbyitscover.com/?r=533",
        "https://thisiswhyimbroke.com/?r=534",
        "https://mapcrunch.com/?r=535",
        "https://littlealchemy2.com/?r=536",
        "https://patatap.com/?r=537",
        "https://onemillioncheckboxes.com/?r=538",
        "https://mackerelmediafish.com/?r=539",
        "https://koalastothemax.com/?r=540",
        "https://neal.fun/?r=541",
        "https://pointerpointer.com/?r=542",
        "https://eelslap.com/?r=543",
        "https://catbounce.com/?r=544",
        "https://corndog.io/?r=545",
        "https://heeeeeeeey.com/?r=546",
        "https://staggeringbeauty.com/?r=547",
        "https://zoomquilt.org/?r=548",
        "https://bouncingdvdlogo.com/?r=549",
        "https://longdogechallenge.com/?r=550",
        "https://hackertyper.com/?r=551",
        "https://findtheinvisiblecow.com/?r=552",
        "https://alwaysjudgeabookbyitscover.com/?r=553",
        "https://thisiswhyimbroke.com/?r=554",
        "https://mapcrunch.com/?r=555",
        "https://littlealchemy2.com/?r=556",
        "https://patatap.com/?r=557",
        "https://onemillioncheckboxes.com/?r=558",
        "https://mackerelmediafish.com/?r=559",
        "https://koalastothemax.com/?r=560",
        "https://neal.fun/?r=561",
        "https://pointerpointer.com/?r=562",
        "https://eelslap.com/?r=563",
        "https://catbounce.com/?r=564",
        "https://corndog.io/?r=565",
        "https://heeeeeeeey.com/?r=566",
        "https://staggeringbeauty.com/?r=567",
        "https://zoomquilt.org/?r=568",
        "https://bouncingdvdlogo.com/?r=569",
        "https://longdogechallenge.com/?r=570",
        "https://hackertyper.com/?r=571",
        "https://findtheinvisiblecow.com/?r=572",
        "https://alwaysjudgeabookbyitscover.com/?r=573",
        "https://thisiswhyimbroke.com/?r=574",
        "https://mapcrunch.com/?r=575",
        "https://littlealchemy2.com/?r=576",
        "https://patatap.com/?r=577",
        "https://onemillioncheckboxes.com/?r=578",
        "https://mackerelmediafish.com/?r=579",
        "https://koalastothemax.com/?r=580",
        "https://neal.fun/?r=581",
        "https://pointerpointer.com/?r=582",
        "https://eelslap.com/?r=583",
        "https://catbounce.com/?r=584",
        "https://corndog.io/?r=585",
        "https://heeeeeeeey.com/?r=586",
        "https://staggeringbeauty.com/?r=587",
        "https://zoomquilt.org/?r=588",
        "https://bouncingdvdlogo.com/?r=589",
        "https://longdogechallenge.com/?r=590",
        "https://hackertyper.com/?r=591",
        "https://findtheinvisiblecow.com/?r=592",
        "https://alwaysjudgeabookbyitscover.com/?r=593",
        "https://thisiswhyimbroke.com/?r=594",
        "https://mapcrunch.com/?r=595",
        "https://littlealchemy2.com/?r=596",
        "https://patatap.com/?r=597",
        "https://onemillioncheckboxes.com/?r=598",
        "https://mackerelmediafish.com/?r=599",
        "https://koalastothemax.com/?r=600",
        "https://neal.fun/?r=601",
        "https://pointerpointer.com/?r=602",
        "https://eelslap.com/?r=603",
        "https://catbounce.com/?r=604",
        "https://corndog.io/?r=605",
        "https://heeeeeeeey.com/?r=606",
        "https://staggeringbeauty.com/?r=607",
        "https://zoomquilt.org/?r=608",
        "https://bouncingdvdlogo.com/?r=609",
        "https://longdogechallenge.com/?r=610",
        "https://hackertyper.com/?r=611",
        "https://findtheinvisiblecow.com/?r=612",
        "https://alwaysjudgeabookbyitscover.com/?r=613",
        "https://thisiswhyimbroke.com/?r=614",
        "https://mapcrunch.com/?r=615",
        "https://littlealchemy2.com/?r=616",
        "https://patatap.com/?r=617",
        "https://onemillioncheckboxes.com/?r=618",
        "https://mackerelmediafish.com/?r=619",
        "https://koalastothemax.com/?r=620",
        "https://neal.fun/?r=621",
        "https://pointerpointer.com/?r=622",
        "https://eelslap.com/?r=623",
        "https://catbounce.com/?r=624",
        "https://corndog.io/?r=625",
        "https://heeeeeeeey.com/?r=626",
        "https://staggeringbeauty.com/?r=627",
        "https://zoomquilt.org/?r=628",
        "https://bouncingdvdlogo.com/?r=629",
        "https://longdogechallenge.com/?r=630",
        "https://hackertyper.com/?r=631",
        "https://findtheinvisiblecow.com/?r=632",
        "https://alwaysjudgeabookbyitscover.com/?r=633",
        "https://thisiswhyimbroke.com/?r=634",
        "https://mapcrunch.com/?r=635",
        "https://littlealchemy2.com/?r=636",
        "https://patatap.com/?r=637",
        "https://onemillioncheckboxes.com/?r=638",
        "https://mackerelmediafish.com/?r=639",
        "https://koalastothemax.com/?r=640",
        "https://neal.fun/?r=641",
        "https://pointerpointer.com/?r=642",
        "https://eelslap.com/?r=643",
        "https://catbounce.com/?r=644",
        "https://corndog.io/?r=645",
        "https://heeeeeeeey.com/?r=646",
        "https://staggeringbeauty.com/?r=647",
        "https://zoomquilt.org/?r=648",
        "https://bouncingdvdlogo.com/?r=649",
        "https://longdogechallenge.com/?r=650",
        "https://hackertyper.com/?r=651",
        "https://findtheinvisiblecow.com/?r=652",
        "https://alwaysjudgeabookbyitscover.com/?r=653",
        "https://thisiswhyimbroke.com/?r=654",
        "https://mapcrunch.com/?r=655",
        "https://littlealchemy2.com/?r=656",
        "https://patatap.com/?r=657",
        "https://onemillioncheckboxes.com/?r=658",
        "https://mackerelmediafish.com/?r=659",
        "https://koalastothemax.com/?r=660",
        "https://neal.fun/?r=661",
        "https://pointerpointer.com/?r=662",
        "https://eelslap.com/?r=663",
        "https://catbounce.com/?r=664",
        "https://corndog.io/?r=665",
        "https://heeeeeeeey.com/?r=666",
        "https://staggeringbeauty.com/?r=667",
        "https://zoomquilt.org/?r=668",
        "https://bouncingdvdlogo.com/?r=669",
        "https://longdogechallenge.com/?r=670",
        "https://hackertyper.com/?r=671",
        "https://findtheinvisiblecow.com/?r=672",
        "https://alwaysjudgeabookbyitscover.com/?r=673",
        "https://thisiswhyimbroke.com/?r=674",
        "https://mapcrunch.com/?r=675",
        "https://littlealchemy2.com/?r=676",
        "https://patatap.com/?r=677",
        "https://onemillioncheckboxes.com/?r=678",
        "https://mackerelmediafish.com/?r=679",
        "https://koalastothemax.com/?r=680",
        "https://neal.fun/?r=681",
        "https://pointerpointer.com/?r=682",
        "https://eelslap.com/?r=683",
        "https://catbounce.com/?r=684",
        "https://corndog.io/?r=685",
        "https://heeeeeeeey.com/?r=686",
        "https://staggeringbeauty.com/?r=687",
        "https://zoomquilt.org/?r=688",
        "https://bouncingdvdlogo.com/?r=689",
        "https://longdogechallenge.com/?r=690",
        "https://hackertyper.com/?r=691",
        "https://findtheinvisiblecow.com/?r=692",
        "https://alwaysjudgeabookbyitscover.com/?r=693",
        "https://thisiswhyimbroke.com/?r=694",
        "https://mapcrunch.com/?r=695",
        "https://littlealchemy2.com/?r=696",
        "https://patatap.com/?r=697",
        "https://onemillioncheckboxes.com/?r=698",
        "https://mackerelmediafish.com/?r=699",
        "https://koalastothemax.com/?r=700",
        "https://neal.fun/?r=701",
        "https://pointerpointer.com/?r=702",
        "https://eelslap.com/?r=703",
        "https://catbounce.com/?r=704",
        "https://corndog.io/?r=705",
        "https://heeeeeeeey.com/?r=706",
        "https://staggeringbeauty.com/?r=707",
        "https://zoomquilt.org/?r=708",
        "https://bouncingdvdlogo.com/?r=709",
        "https://longdogechallenge.com/?r=710",
        "https://hackertyper.com/?r=711",
        "https://findtheinvisiblecow.com/?r=712",
        "https://alwaysjudgeabookbyitscover.com/?r=713",
        "https://thisiswhyimbroke.com/?r=714",
        "https://mapcrunch.com/?r=715",
        "https://littlealchemy2.com/?r=716",
        "https://patatap.com/?r=717",
        "https://onemillioncheckboxes.com/?r=718",
        "https://mackerelmediafish.com/?r=719",
        "https://koalastothemax.com/?r=720",
        "https://neal.fun/?r=721",
        "https://pointerpointer.com/?r=722",
        "https://eelslap.com/?r=723",
        "https://catbounce.com/?r=724",
        "https://corndog.io/?r=725",
        "https://heeeeeeeey.com/?r=726",
        "https://staggeringbeauty.com/?r=727",
        "https://zoomquilt.org/?r=728",
        "https://bouncingdvdlogo.com/?r=729",
        "https://longdogechallenge.com/?r=730",
        "https://hackertyper.com/?r=731",
        "https://findtheinvisiblecow.com/?r=732",
        "https://alwaysjudgeabookbyitscover.com/?r=733",
        "https://thisiswhyimbroke.com/?r=734",
        "https://mapcrunch.com/?r=735",
        "https://littlealchemy2.com/?r=736",
        "https://patatap.com/?r=737",
        "https://onemillioncheckboxes.com/?r=738",
        "https://mackerelmediafish.com/?r=739",
        "https://koalastothemax.com/?r=740",
        "https://neal.fun/?r=741",
        "https://pointerpointer.com/?r=742",
        "https://eelslap.com/?r=743",
        "https://catbounce.com/?r=744",
        "https://corndog.io/?r=745",
        "https://heeeeeeeey.com/?r=746",
        "https://staggeringbeauty.com/?r=747",
        "https://zoomquilt.org/?r=748",
        "https://bouncingdvdlogo.com/?r=749",
        "https://longdogechallenge.com/?r=750",
        "https://hackertyper.com/?r=751",
        "https://findtheinvisiblecow.com/?r=752",
        "https://alwaysjudgeabookbyitscover.com/?r=753",
        "https://thisiswhyimbroke.com/?r=754",
        "https://mapcrunch.com/?r=755",
        "https://littlealchemy2.com/?r=756",
        "https://patatap.com/?r=757",
        "https://onemillioncheckboxes.com/?r=758",
        "https://mackerelmediafish.com/?r=759",
        "https://koalastothemax.com/?r=760",
        "https://neal.fun/?r=761",
        "https://pointerpointer.com/?r=762",
        "https://eelslap.com/?r=763",
        "https://catbounce.com/?r=764",
        "https://corndog.io/?r=765",
        "https://heeeeeeeey.com/?r=766",
        "https://staggeringbeauty.com/?r=767",
        "https://zoomquilt.org/?r=768",
        "https://bouncingdvdlogo.com/?r=769",
        "https://longdogechallenge.com/?r=770",
        "https://hackertyper.com/?r=771",
        "https://findtheinvisiblecow.com/?r=772",
        "https://alwaysjudgeabookbyitscover.com/?r=773",
        "https://thisiswhyimbroke.com/?r=774",
        "https://mapcrunch.com/?r=775",
        "https://littlealchemy2.com/?r=776",
        "https://patatap.com/?r=777",
        "https://onemillioncheckboxes.com/?r=778",
        "https://mackerelmediafish.com/?r=779",
        "https://koalastothemax.com/?r=780",
        "https://neal.fun/?r=781",
        "https://pointerpointer.com/?r=782",
        "https://eelslap.com/?r=783",
        "https://catbounce.com/?r=784",
        "https://corndog.io/?r=785",
        "https://heeeeeeeey.com/?r=786",
        "https://staggeringbeauty.com/?r=787",
        "https://zoomquilt.org/?r=788",
        "https://bouncingdvdlogo.com/?r=789",
        "https://longdogechallenge.com/?r=790",
        "https://hackertyper.com/?r=791",
        "https://findtheinvisiblecow.com/?r=792",
        "https://alwaysjudgeabookbyitscover.com/?r=793",
        "https://thisiswhyimbroke.com/?r=794",
        "https://mapcrunch.com/?r=795",
        "https://littlealchemy2.com/?r=796",
        "https://patatap.com/?r=797",
        "https://onemillioncheckboxes.com/?r=798",
        "https://mackerelmediafish.com/?r=799",
        "https://koalastothemax.com/?r=800",
        "https://neal.fun/?r=801"],
        website => !website.includes("theuselessweb.com")
  );
});
